@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMWUzZTY1YWU0Zjk4MGRhMDk0Y2ViZSIsImlhdCI6MTYxMjU5NTU4NywiZXhwIjoxNjEyNTk1ODg3fQ.LwlkDAvrwtVTkryD2_Xl-FxviRjsWJZl5hFj0E4mgaY

### COMPRAR VOO
POST http://localhost:5000/checkout
Content-Type: application/json
authorization: {{token}}

{
  "purchase":{
    "flight1": "601e10c0af86262130a6b0c4",
    "passengers": 3,
    "cost": 25
  }
}


### GET MY FLIGHTS
POST http://localhost:5000/voo/mine
Content-Type: application/json
authorization: {{token}}


### GET ALL FLIGHTS
GET http://localhost:5000/voo/all


### CREATE FLIGHT
POST http://localhost:5000/voo
Content-Type: application/json

{
  "faresMoney": 60,
  "faresMiles": 1000,
  "fares": "$30.00 - 3000 miles",
  "origin": "GRU",
  "destination": "LAX",
  "departure1": "2021/05/05",
  "passengers": 50
}

### CREATE USER
PUT http://localhost:5000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin@123",
  "money": 50000
}

### LOGIN
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin@123"
}

### GET AEROPORTOS
GET http://localhost:5000/locations

### CREATE AEROPORTO
POST http://localhost:5000/aeroporto
Content-Type: application/json

{
  "code": "POA",
  "name": "Salgado Filho",
  "city": "Porto Alegre",
  "country": "Brazil",
  "timezone": "America/Sao_Paulo"
}