@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMWUzZTY1YWU0Zjk4MGRhMDk0Y2ViZSIsImlhdCI6MTYxMjY3MzYwOCwiZXhwIjoxNjEyNjczOTA4fQ.OvBGFVYibSiT4rxxrqI2WnRZ9tVPXU4QB2aJ1j1DPtI


### COMPRAR VOO
POST http://localhost:5000/checkout
Content-Type: application/json
authorization: {{token}}

{
  "purchase":{
    "flight1": "601f5c73caa1e63accf945ee",
    "passengers": 3,
    "cost": 25
  }
}

### CREATE USER
PUT http://localhost:5000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin@123",
  "money": 50000
}

### LOGIN
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin@123"
}


### GET FLIGHT
GET http://localhost:5000/search/?origin=GRU&destination=LAX&departure1=2021/05/05&passengers=3
Content-Type: application/json


### GET MY FLIGHTS
GET http://localhost:5000/my-flights/
Content-Type: application/json
authorization: {{token}}


### GET FLIGHTS
GET http://localhost:5000/voo/?&page=3

### GET ALL FLIGHTS
GET http://localhost:5000/voo/all

### GET AEROPORTOS
GET http://localhost:5000/locations

### CREATE AEROPORTO
POST http://localhost:5000/aeroporto
Content-Type: application/json

{
  "code": "POA",
  "name": "Salgado Filho",
  "city": "Porto Alegre",
  "country": "Brazil",
  "timezone": "America/Sao_Paulo"
}
### CREATE FLIGHT
POST http://localhost:5000/voo
Content-Type: application/json

{
  "faresMoney": 600,
  "faresMiles": 1500,
  "origin": "MAO",
  "destination": "GRU",
  "departure1": "2021/12/09",
  "passengers": 300
}