### COMPRAR VOO
POST http://localhost:5000/checkout
Content-Type: application/json
Authorization: 

{
  "purchase":{
    "flight1": "601df9857eafe116b08fd5d4",
    "fare1": string,
    "flight2": "601e04551094693084547a66",
    "fare2": string,
    "passengers": number,
    "total": {
      miles: number,
      money: number
    }
  }
}


### GET MY FLIGHTS
POST http://localhost:5000/voo/mine
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMWRjYzNlYTE2NTZkMDU3ODk0Yjk3NiIsImlhdCI6MTYxMjU2NzM1NywiZXhwIjoxNjEyNTY3NjU3fQ.XNyJHi_XG6vDCyXiEf1yiKN2ncMw-oxrR7oEDfkIN2A


### GET ALL FLIGHTS
GET http://localhost:5000/voo/all


### CREATE FLIGHT
POST http://localhost:5000/voo
Content-Type: application/json

{
  "leg": ["LAX"],
  "faresMoney": 60,
  "faresMiles": 1000,
  "fares": "$30.00 - 3000 miles",
  "origin": "GRU",
  "destination": "LAX",
  "departure1": "2021/05/05",
  "passengers": 50
}

### CREATE USER
PUT http://localhost:5000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin@123"
}

### LOGIN
POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin@123"
}

### GET AEROPORTOS
GET http://localhost:5000/locations

### CREATE AEROPORTO
POST http://localhost:5000/aeroporto
Content-Type: application/json

{
  "code": "POA",
  "name": "Salgado Filho",
  "city": "Porto Alegre",
  "country": "Brazil",
  "timezone": "America/Sao_Paulo"
}